#!/bin/sh

#
# Installation script for spseqload
#
# 1) cp spseqload.config.default spseqload.config
# 2) cp trseqload.config.default trseqload.config
# 3) cp sp_common.config.default sp_common.config
# 2) Install 
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

#
# Make sure config files exist
#
cd `dirname $0`

# establish the three config files
SP_CONFIG=spseqload.config
TR_CONFIG=trseqload.config 
COMMON_CONFIG=sp_common.config

# Make sure sp_common.config file exists and source it
if [ -r ${COMMON_CONFIG} ]
then
    echo "Source ${COMMON_CONFIG}"
    . ${COMMON_CONFIG}
else
    echo "Cannot source configuration file: ${COMMON_CONFIG}"
    installFailed
fi

# Make sure spseqload.config file exists and source it
if [ -r ${SP_CONFIG} ]
then
    echo "Source ${SP_CONFIG}"
    . ${SP_CONFIG}
else
    echo "Cannot source configuration file: ${SP_CONFIG}"
    installFailed
fi

#
# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for spseqload
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# Create the input directory if it doesn't exist.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi

#
# Create symbolic link to input file from INPUTDIR
#
rm -f ${APP_INFILE}
ln -s  ${UNIPROTDIR}/${FILENAME} ${APP_INFILE}

# now do trseqload
# Make sure trseqload.config file exists and source it
if [ -r ${TR_CONFIG} ]
then
    echo "Source ${TR_CONFIG}"
    . ${TR_CONFIG}
else
    echo "Cannot source configuration file: ${TR_CONFIG}"
    installFailed
fi

# source sp_common.config again
. ${COMMON_CONFIG}

#
# Create the input directory if it doesn't exist.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi

#
# Create symbolic link to input file from INPUTDIR
#
rm -f ${APP_INFILE}
ln -s  ${UNIPROTDIR}/${FILENAME} ${APP_INFILE}

#
# run DLAInstall for trseqload
#
${DLAINSTALL} ${DEV}

